from util.activity import *

activities_list_3 = [ #3, 4, 5, 7,
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    Activity.BSC_POLYGON_ZKMESSENGER,
    Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_4 = [ #3, 4, 5, 7,
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    Activity.BSC_POLYGON_ZKMESSENGER,
    Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_5 = [ #3, 4, 5, 7,
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    Activity.BSC_POLYGON_ZKMESSENGER,
    Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_6 = [ #6
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    Activity.BSC_POLYGON_ZKMESSENGER,
    # Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_7 = [ #3, 4, 5, 7,
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    Activity.BSC_POLYGON_ZKMESSENGER,
    Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_8 = [ #8
    Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    # Activity.BSC_POLYGON_ZKMESSENGER,
    # Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    # Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_9 = [ #9
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    # Activity.BSC_POLYGON_ZKMESSENGER,
    Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    # Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

activities_list_10 = [ #10
    # Activity.GREENFIELD_TESTNET_MINT, 
    Activity.OP_BNB_MINT_OPERATIONS,
    # Activity.PANDRA_CODECONQUEROR_OPERATIONS,
    # Activity.PANDRA_PIXELBROWLER_OPERATIONS,
    # Activity.PANDRA_MELODYMAVEN_OPERATIONS,
    # Activity.PANDRA_ECOGUARDIAN_OPERATIONS,
    Activity.MAINNET_ALPHA_NFT_CORE_DAO_OPERATIONS,
    # Activity.BSC_POLYGON_ZKMESSENGER,
    # Activity.ZK_LIGHT_CLIENT_NFT_OPERATIONS,
    Activity.BNB_CHAIN_LUBAN_NFT_OPERATIONS
]

ALL_ADDRESS_ACTIVITY_ARRAY = [
    activities_list_3,
    activities_list_4,
    activities_list_5,
    activities_list_6,
    activities_list_7,
    activities_list_8,
    activities_list_9,
    activities_list_10
]