from enum import Enum


class Chain():
    ARBITRUM = 'arbitrum'
    ARBITRUM_NOVA = 'arbitrum_nova'
    AVALANCHE = 'avalanche'
    BSC = 'bsc'
    CELO = 'celo'
    COMBO = 'combo'
    CORE = 'core'
    DFK = 'dfk'
    ETH = 'eth'
    FANTOM = 'fantom'
    GNOSIS = 'gnosis'
    HARMONY = 'harmony'
    KLAYTN = 'klaytn'
    METIS = 'metis'
    MOONBEAM = 'moonbeam'
    MOONRIVER = 'moonriver'
    OP_BNB = 'op_bnb'
    OPTIMISM = 'optimism'
    POLYGON = 'polygon'
    POLYGON_ZKEVM = 'polygon_zkevm'
    ZK_SYNC = 'zk_sync'